# PumaGuard settings
alpha: 1.0e-05
base-data-directory: ../data
batch-size: 16
color-mode: rgb
epochs: 300
image-dimensions:
- 512
- 512
lion-directories:
- lion
- cougar
- stable/angle 1/lion
- stable/angle 2/lion
- stable/angle 3/lion
- stable/angle 4/lion
model-function: light-3-model
model-version: light-3
no-lion-directories:
- no_lion
- nocougar
- stable/angle 1/no-lion
- stable/angle 2/no-lion
- stable/angle 3/no-lion
- stable/angle 4/no-lion
notebook: 9
with-augmentation: false
