# PumaGuard settings
alpha: 0.0001
batch-size: 32
color-mode: rgb
epochs: 500
image-dimensions:
- 512
- 512
lion-directories:
- /mnt/c/Users/adisb/PumaGuard Training/NPS/lion/
- /mnt/c/Users/adisb/PumaGuard Training/Stables/lion/
model-function: xception
model-version: pre-trained
no-lion-directories:
- /mnt/c/Users/adisb/PumaGuard Training/NPS/no-lion/
- /mnt/c/Users/adisb/PumaGuard Training/Stables/no-lion
notebook: 8
validation-lion-directories: []
validation-no-lion-directories: []
with-augmentation: false
