# PumaGuard settings
alpha: 0.0001
base-data-directory: ../training-data
file-stabilization-extra-wait: 0
YOLO-min-size: 0.02
YOLO-conf-thresh: 0.25
YOLO-max-dets: 2
classifier-model-filename: colorbw_111325.h5
deterrent-sound-file: deterrent_puma.mp3
batch-size: 16
color-mode: rgb
epochs: 300
image-dimensions:
- 512
- 512
lion-directories:
- lion
- cougar
model-function: xception
model-version: pre-trained
no-lion-directories:
- no_lion
- nocougar
notebook: 6
with-augmentation: false
